server:
  port: 8765
  
spring:
  application:
    name: api-gateway
    
eureka:
  client:
    service-url:      defaultZone: http://localhost:8761/eureka/
zuul:  sensitive-headers: 'Cookie,Set-Cookie'
  routes:
    security-service:
      path: /auth/**
      service-id: SECURITY-SERVICE
      #url: http://localhost:8081
      strip-prefix: false

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

    
